services:
  - type: web
    name: cs-unification-examtest
    env: node
    region: oregon
    buildCommand: npm install && npm run build && npm run db:push
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: cs-examtest-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /api/courses

databases:
  - name: cs-examtest-db
    databaseName: cs_examtest
    user: cs_examtest_user